# Generated by Django 6.0.6 on 2026-06-17 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='chat.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
